# Generated by Django 4.2 on 2023-05-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_order_discounr_orders_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsaddress',
            name='Students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_addresses', to='users.students'),
        ),
    ]
